# اسم التطبيق
app.name=Bounce Up

# معرف التطبيق الفريد (تم إزالة المسافة لأن المسافات غير مسموحة في package name)
app.application_id=com.dkhel.bounceup

# تحويل الاتجاه إلى طولي
app.orientation=portrait

# إصدار البناء
app.version_code=1
app.version_name=1.0

# خيارات Gradle
android.enableJetifier=false
android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g
android.javaCompile.suppressSourceTargetDeprecationWarning=true